name: Daily Combined Logger

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  log_combined:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run log-value.js
        run: node log-value.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add log.csv

          if git diff --cached --quiet; then
            echo "⏩ No changes to commit."
          else
            git commit -m "📊 Add combined value for $(date +'%Y-%m-%d')"
            git push origin HEAD:main
          fi
